development:
  adapter: sqlite3
  encoding: unicode
  database: magic_realm_production
  pool: 5

test:
  adapter: sqlite3
  encoding: unicode
  database: magic_realm_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: Magic_Realm_production
  pool: 5
